Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/giulio/DRUBER/src/experiments/simulate.py", line 34, in <module>
    solution = S.run(args.algorithm, args.method)
  File "/home/giulio/DRUBER/src/simulation/Simulator.py", line 129, in run
    if not os.path.exists(self.outFOLDER): os.makedirs(self.outFOLDER)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: './out/Small/S5D2U3/10'
